<?php

use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BitcoinSettlementController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\EscrowController as AdminEscrowController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\MenuItemController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\PaymentGatewayConfigController;
use App\Http\Controllers\Admin\PaymentGatewayController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductReviewController;
use App\Http\Controllers\Admin\ProductVariantController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RefundController;
use App\Http\Controllers\Admin\SocialMediaLinkController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\BitcoinCheckoutController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\EscrowController;
use App\Http\Controllers\SiteSettingsController;
use App\Http\Controllers\Vendor\BitcoinPayoutController;
use App\Http\Controllers\Vendor\BitcoinPayoutVerificationController;
use App\Http\Controllers\Vendor\OrderShippingController;
use App\Http\Controllers\Vendor\ProductShippingController;
use App\Http\Controllers\Vendor\ShippingController;
use App\Http\Controllers\VendorRegistrationFeeController;
use App\Http\Controllers\VendorProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/login', function () { return view('admin.auth.login'); });
Auth::routes();

Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::post('/categories/data', [CategoryController::class, 'getCategories'])->name('categories.data');
    Route::post('/admin/categories/update-status', [CategoryController::class, 'updateCategoryStatus'])->name('categories.updateStatus');
    Route::resource('products', ProductController::class);
    Route::post('products/data', [ProductController::class, 'getProducts'])->name('products.data');
    Route::post('admin/products/updateStatus', [ProductController::class, 'updateStatus'])->name('products.updateStatus');
    Route::get('/brands', [BrandController::class, 'index'])->name('brands.index');
    Route::get('admin/brands/getdata', [BrandController::class, 'getData'])->name('brands.getData');
    Route::get('brands/{id}/edit', [BrandController::class, 'edit'])->name('brands.edit');
    Route::put('brands/{brand}', [BrandController::class, 'update'])->name('brands.update');
    Route::get('brands/create', [BrandController::class, 'create'])->name('brands.create');
    Route::post('brands', [BrandController::class, 'store'])->name('brands.store');
    Route::delete('brands/{id}', [BrandController::class, 'destroy'])->name('brands.destroy');
    Route::post('brands/update-status', [BrandController::class, 'updateStatus'])->name('brands.updateStatus');
    Route::post('/change-language', [LanguageController::class, 'changeLanguage'])->name('change.language');
    Route::resource('menus', MenuController::class);
    Route::post('menus/data', [MenuController::class, 'getData'])->name('menus.data');
    Route::resource('menus.items', MenuItemController::class)->shallow();
    Route::get('menus-items', [MenuItemController::class, 'index'])->name('menus.item.index');
    Route::post('menus-items/getdata', [MenuItemController::class, 'getData'])->name('menus.item.getData');
    Route::resource('banners', BannerController::class);
    Route::post('banners/data', [BannerController::class, 'getData'])->name('banners.data');
    Route::put('/banners/toggle-status/{id}', [BannerController::class, 'toggleStatus'])->name('banners.toggleStatus');
    Route::post('/banners/update-status', [BannerController::class, 'updateStatus'])->name('banners.updateStatus');
    Route::resource('social-media-links', SocialMediaLinkController::class);
    Route::post('social-media-links/data', [SocialMediaLinkController::class, 'getData'])->name('social-media-links.data');
    Route::get('orders', [OrderController::class, 'index'])->name('orders.index');
    Route::delete('orders/{id}', [OrderController::class, 'destroy'])->name('orders.destroy');
    Route::post('orders/data', [OrderController::class, 'getData'])->name('orders.data');
    Route::resource('product_variants', ProductVariantController::class);
    Route::post('/product_variants/data', [ProductVariantController::class, 'getData'])->name('product_variants.data');
    Route::resource('customers', CustomerController::class);
    Route::get('admin/customers/data', [CustomerController::class, 'getCustomerData'])->name('customers.data');
    Route::get('/reviews/data', [ProductReviewController::class, 'getData'])->name('reviews.data');
    Route::resource('reviews', ProductReviewController::class)->except(['create', 'store']);
    Route::resource('attributes', AttributeController::class);
    Route::post('attributes/{attribute}/values', [AttributeController::class, 'storeValue'])->name('attributes.values.store');
    Route::delete('values/{value}', [AttributeController::class, 'destroy'])->name('values.destroy');
    Route::post('attributes/data', [AttributeController::class, 'getAttributesData'])->name('attributes.data');
    Route::post('values/{value}/translations', [AttributeController::class, 'storeTranslation'])->name('values.translations.store');
    Route::delete('translations/{translation}', [AttributeController::class, 'destroy'])->name('translations.destroy');
    Route::get('vendors', [VendorController::class, 'index'])->name('vendors.index');
    Route::get('vendors/data', [VendorController::class, 'getVendorData'])->name('vendors.data');
    Route::post('vendors/{id}/status', [VendorController::class, 'updateStatus'])->name('vendors.status');
    Route::delete('vendors/{id}', [VendorController::class, 'destroy'])->name('vendors.destroy');
    Route::get('vendors/create', [VendorController::class, 'create'])->name('vendors.create');
    Route::post('vendors', [VendorController::class, 'store'])->name('vendors.store');
    Route::resource('pages', PageController::class);
    Route::post('pages/update-status', [PageController::class, 'updatePageStatus'])->name('pages.updateStatus');
    Route::post('pages/data', [PageController::class, 'data'])->name('pages.data');
    Route::get('payments/get-data', [PaymentController::class, 'getData'])->name('payments.getData');
    Route::resource('payments', PaymentController::class)->only(['index', 'destroy', 'show']);
    Route::get('refunds', [RefundController::class, 'index'])->name('refunds.index');
    Route::get('refunds/data', [RefundController::class, 'getData'])->name('refunds.getData');
    Route::delete('refunds/{refund}', [RefundController::class, 'destroy'])->name('refunds.destroy');
    Route::get('refunds/{refund}', [RefundController::class, 'show'])->name('refunds.show');
    Route::get('payment-gateways', [PaymentGatewayController::class, 'index'])->name('payment-gateways.index');
    Route::get('payment-gateways/data', [PaymentGatewayController::class, 'getData'])->name('payment-gateways.getData');
    Route::get('payment-gateways/{paymentGateway}/edit', [PaymentGatewayController::class, 'edit'])->name('payment-gateways.edit');
    Route::put('payment-gateways/{paymentGateway}', [PaymentGatewayController::class, 'update'])->name('payment-gateways.update');
    Route::delete('payment-gateways/{paymentGateway}', [PaymentGatewayController::class, 'destroy'])->name('payment-gateways.destroy');
    Route::get('payment_gateway_configs/getData', [PaymentGatewayConfigController::class, 'getData'])->name('payment_gateway_configs.getData');
    Route::resource('payment_gateway_configs', PaymentGatewayConfigController::class)->except(['show']);
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('escrow', [AdminEscrowController::class, 'index'])->name('escrow.index');
    Route::post('escrow/{escrow}/release', [AdminEscrowController::class, 'release'])->name('escrow.release');
    Route::post('escrow/{escrow}/refund', [AdminEscrowController::class, 'refund'])->name('escrow.refund');
    Route::post('escrow/disputes/{dispute}/resolve', [AdminEscrowController::class, 'resolveDispute'])->name('admin.escrow.disputes.resolve');
    Route::get('bitcoin/settlements', [BitcoinSettlementController::class, 'index'])->name('bitcoin.settlements.index');
    Route::post('bitcoin/vendors/{vendor}/verify', [BitcoinSettlementController::class, 'verifyVendor'])->name('bitcoin.vendors.verify');
    Route::post('bitcoin/settlements/{settlement}/destination', [BitcoinSettlementController::class, 'destination'])->name('bitcoin.settlements.destination');
    Route::post('bitcoin/settlements/{settlement}/submit', [BitcoinSettlementController::class, 'submit'])->name('bitcoin.settlements.submit');
    Route::post('bitcoin/settlements/{settlement}/approve', [BitcoinSettlementController::class, 'approve'])->name('bitcoin.settlements.approve');
    Route::post('bitcoin/settlements/{settlement}/sync', [BitcoinSettlementController::class, 'sync'])->name('bitcoin.settlements.sync');
});

Route::middleware(['auth:vendor', 'vendor.can_sell'])->prefix('vendor')->name('vendor.')->group(function () {
    Route::get('/registration-fee', [VendorRegistrationFeeController::class, 'show'])->name('registration-fee');
    Route::get('/shipping', [ShippingController::class, 'index'])->name('shipping');
    Route::post('/shipping/zones', [ShippingController::class, 'storeZone'])->name('shipping.zones.store');
    Route::post('/shipping/rates', [ShippingController::class, 'storeRate'])->name('shipping.rates.store');
    Route::delete('/shipping/zones/{zone}', [ShippingController::class, 'destroyZone'])->name('shipping.zones.destroy');
    Route::delete('/shipping/rates/{rate}', [ShippingController::class, 'destroyRate'])->name('shipping.rates.destroy');
    Route::get('/products/{product}/shipping', [ProductShippingController::class, 'index'])->name('products.shipping');
    Route::put('/products/{product}/shipping', [ProductShippingController::class, 'update'])->name('products.shipping.update');
    Route::put('/orders/{order}/shipping', [OrderShippingController::class, 'update'])->name('orders.shipping.update');
    Route::get('/bitcoin/payout-address', [BitcoinPayoutController::class, 'edit'])->name('bitcoin.payout.edit');
    Route::put('/bitcoin/payout-address', [BitcoinPayoutController::class, 'update'])->name('bitcoin.payout.update');
    Route::get('/bitcoin/payouts', [BitcoinPayoutController::class, 'index'])->name('bitcoin.payouts');
    Route::get('/bitcoin/payout-address/verify', [BitcoinPayoutVerificationController::class, 'show'])->name('bitcoin.payout.verify');
    Route::post('/bitcoin/payout-address/verify/request', [BitcoinPayoutVerificationController::class, 'requestVerification'])->name('vendor.bitcoin.payout.verify.request');
    Route::post('/bitcoin/payout-address/verify/confirm', [BitcoinPayoutVerificationController::class, 'confirm'])->name('vendor.bitcoin.payout.verify.confirm');
});

Route::middleware(['auth:customer'])->group(function () {
    Route::get('/chat', [ChatController::class, 'index'])->name('chat.index');
    Route::post('/chat/vendor/{vendor}', [ChatController::class, 'start'])->name('chat.start');
    Route::get('/chat/{conversation}', [ChatController::class, 'show'])->name('chat.show');
    Route::post('/chat/{conversation}/messages', [ChatController::class, 'send'])->name('chat.send');
    Route::get('/checkout', [BitcoinCheckoutController::class, 'index'])->name('checkout.index');
    Route::get('/checkout/shipping-options', [BitcoinCheckoutController::class, 'shippingOptions'])->name('checkout.shipping-options');
    Route::post('/checkout/process', [BitcoinCheckoutController::class, 'process'])->name('checkout.process');
});

Route::middleware(['auth:vendor', 'vendor.can_sell'])->group(function () {
    Route::get('/vendor/chat', [ChatController::class, 'index'])->name('vendor.chat.index');
    Route::get('/vendor/chat/{conversation}', [ChatController::class, 'show'])->name('vendor.chat.show');
    Route::post('/vendor/chat/{conversation}/messages', [ChatController::class, 'send'])->name('vendor.chat.send');
});

Route::middleware('auth:customer')->group(function () {
    Route::post('/escrow/orders/{order}', [EscrowController::class, 'create'])->name('escrow.create');
    Route::get('/escrow/{escrow}', [EscrowController::class, 'show'])->name('escrow.show');
    Route::post('/escrow/{escrow}/payment', [EscrowController::class, 'createPayment'])->name('escrow.payment');
    Route::post('/escrow/{escrow}/confirm-receipt', [EscrowController::class, 'confirmReceipt'])->name('escrow.confirm-receipt');
    Route::post('/escrow/{escrow}/dispute', [EscrowController::class, 'dispute'])->name('escrow.dispute');
});

Route::post('/bitcoin/btcpay/webhook', [EscrowController::class, 'webhook'])->name('bitcoin.btcpay.webhook');
Route::get('/vendors/{pseudonym}', [VendorProfileController::class, 'show'])->name('vendors.profile');
Route::get('site-settings', [SiteSettingsController::class, 'index'])->name('site-settings.index');
Route::get('site-settings/edit', [SiteSettingsController::class, 'edit'])->name('admin.site-settings.edit');
Route::put('site-settings/update', [SiteSettingsController::class, 'update'])->name('admin.site-settings.update');
