apiVersion: v1
kind: ConfigMap
metadata:
  name: kosher-market-config
  namespace: kosher-market
data:
  APP_ENV: production
  APP_DEBUG: "false"
  LOG_CHANNEL: stderr
  CACHE_STORE: redis
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: kosher_market
  REDIS_CLIENT: phpredis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CACHE_DB: "1"
