apiVersion: batch/v1
kind: Job
metadata:
  name: kosher-market-migrate
  namespace: kosher-market
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/faraimupfuti/kosher-market:latest
          imagePullPolicy: Always
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: kosher-market-config
            - secretRef:
                name: kosher-market-secrets
