<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bitcoin Escrow #{{ $escrow->id }} | Velstore</title><style>body{font-family:system-ui,sans-serif;background:#f5f7fb;color:#111827;margin:0}.wrap{max-width:800px;margin:40px auto;padding:20px}.card{background:white;border-radius:16px;padding:28px;box-shadow:0 8px 25px #00000012;margin-bottom:18px}.badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#eef2ff;font-weight:700;text-transform:uppercase;font-size:12px}.btc{font-size:30px;font-weight:800}.address{word-break:break-all;background:#f3f4f6;padding:14px;border-radius:8px;font-family:monospace}.qr{width:180px;height:180px;display:block;margin:20px auto}.btn{display:inline-block;padding:12px 16px;border:0;border-radius:8px;background:#111827;color:white;text-decoration:none;font-weight:700;cursor:pointer}.danger{background:#991b1b}.success{background:#166534}.muted{color:#6b7280}.notice{padding:14px;border-radius:10px;background:#fff7ed;margin:16px 0}</style></head>
<body><div class="wrap">
<div class="card"><span class="badge">{{ $escrow->status }}</span><h1>Bitcoin Escrow #{{ $escrow->id }}</h1><p class="muted">Order #{{ $escrow->order_id }}</p><div class="btc">{{ number_format((float)$escrow->amount,8) }} BTC</div><p>Platform fee: {{ number_format((float)$escrow->platform_fee,8) }} BTC</p><p>Seller amount: {{ number_format((float)$escrow->seller_amount,8) }} BTC</p></div>
@if($escrow->status === 'pending')<div class="card"><h2>Pay with Bitcoin</h2><p>Send exactly the requested amount through the secure BTCPay payment page.</p>@php $invoice=session('bitcoin_invoice'); @endphp @if($invoice && !empty($invoice['checkoutLink']))<a class="btn" href="{{ $invoice['checkoutLink'] }}" target="_blank" rel="noopener">Open Bitcoin Payment</a>@else<form method="POST" action="{{ route('escrow.payment',$escrow) }}">@csrf<button class="btn" type="submit">Generate Bitcoin Payment</button></form>@endif<div class="notice">Your Bitcoin is held in escrow after confirmation. It is not immediately paid to the seller.</div></div>@endif
@if($escrow->bitcoin_payment_address)<div class="card"><h2>Payment address</h2><div class="address">{{ $escrow->bitcoin_payment_address }}</div></div>@endif
@if($escrow->status === 'funded')<div class="card"><h2>Order funded</h2><p>Your Bitcoin payment has been confirmed. Confirm receipt when you have received the product/service.</p><form method="POST" action="{{ route('escrow.confirm-receipt',$escrow) }}" style="display:inline">@csrf<button class="btn success" type="submit">Confirm Receipt & Release</button></form><p class="muted">If there is a problem, open a dispute instead of releasing the funds.</p></div><div class="card"><h2>Open a dispute</h2><form method="POST" action="{{ route('escrow.dispute',$escrow) }}">@csrf<input name="reason" required maxlength="100" placeholder="Reason" style="padding:12px;width:90%;margin-bottom:10px"><textarea name="description" required maxlength="5000" placeholder="Describe the issue" style="padding:12px;width:90%;height:100px"></textarea><br><button class="btn danger" type="submit">Open Dispute</button></form></div>@endif
@if($escrow->status === 'disputed')<div class="card"><h2>Dispute under review</h2><p>Velstore administration will review the evidence and determine whether the escrow is released or refunded.</p></div>@endif
</div></body></html>
